# Generated by Django 4.1.3 on 2022-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_service", "0003_alter_dish_options_alter_dish_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/images"),
        ),
    ]
