# Generated by Django 4.1.3 on 2022-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_service", "0004_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, upload_to="restaurant/static/images"),
        ),
    ]
