# Generated by Django 4.1.3 on 2022-11-21 15:31

from django.db import migrations, models
import restaurant_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_service", "0006_alter_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=restaurant_service.models.dish_image_file_path,
            ),
        ),
    ]
