# Generated by Django 4.1.3 on 2022-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_service", "0007_alter_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/dishes/"),
        ),
    ]
